[package]
name = "cauchy"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]
edition = "2018"

[dependencies]
num-traits = "0.2"
serde = "1"

[dependencies.num-complex]
version = "0.2.1"
features = ["serde"]
